version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: essay_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: essay_test_db
      MYSQL_USER: essay_user
      MYSQL_PASSWORD: essay_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: essay_test_adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  app:
    build: .
    container_name: essay_test_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=essay_user
      - DB_PASSWORD=essay_password
      - DB_NAME=essay_test_db
      - SERVER_PORT=5000
      - ENVIRONMENT=development
      - LOG_LEVEL=info
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql_data: 