# .github/workflows/main.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # 複数のNode.jsバージョンでテストする場合

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # npmのキャッシュを有効にする

    - name: Install dependencies
      run: npm ci # package-lock.jsonに基づいてクリーンインストール

    - name: Build project (if applicable)
      run: npm run build --if-present # buildスクリプトがあれば実行

    - name: Run tests
      run: npm test
