# .github/workflows/main.yml

name: Node.js CI

# ワークフローが実行されるトリガーを指定
on:
  push:
    branches: [ main ] # mainブランチへのpush時
  pull_request:
    branches: [ main ] # mainブランチへのpull request時

# 実行されるジョブを定義
jobs:
  build-and-test: # ジョブID
    # ジョブを実行するランナーを指定
    runs-on: ubuntu-latest

    # 複数のNode.jsバージョンでテストするための戦略
    strategy:
      matrix:
        node-version: [18.x, 20.x] # ここでテストしたいNode.jsのバージョンを指定

    # ジョブのステップを定義
    steps:
    # ステップ1: リポジトリのコードをチェックアウトする
    - name: Checkout code
      uses: actions/checkout@v4

    # ステップ2: 指定したNode.jsバージョンをセットアップする
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # npmの依存関係をキャッシュしてビルドを高速化

    # ステップ3: 依存関係をインストールする
    # npm ci は package-lock.json を使ってクリーンインストールを行います
    - name: Install dependencies
      run: npm ci

    # ステップ4: プロジェクトをビルドする (package.jsonにbuildスクリプトがある場合)
    - name: Build project (if applicable)
      run: npm run build --if-present # buildスクリプトが存在すれば実行

    # ステップ5: テストを実行する (package.jsonにtestスクリプトがある場合)
    - name: Run tests
      run: npm test
